// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	RESEND_API: string;
	MAIN_EMAIL: string;
	ADMIN_EMAIL: string;
	DB_URL: string;
}
