CREATE TABLE "organization" (
	"id" serial PRIMARY KEY NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"phoneNumber" text,
	"email" text,
	"type" text,
	"category" text,
	"licenseNumber" text,
	"website" text,
	"address" text,
	"city" text,
	"neighbor" text,
	"street" text,
	"map" text,
	"repName" text,
	"repPhoneNumber" text,
	"repEmail" text,
	"logo" text,
	"officialDocs" text,
	"operationalPlanImage" text,
	"repSpeach" text,
	"licenseImage" text,
	"contractImage" text,
	"additionalDocs" text,
	"financialIndicatorsSetting" numeric,
	"operationalIndicatorsSetting" numeric,
	"corporateIndicatorsSetting" numeric,
	"generalndicatorsSetting" numeric
);
