CREATE TABLE "corporateEntries" (
	"id" text PRIMARY KEY NOT NULL,
	"clientId" text NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp,
	"COMPLIANCE_ADHERENCE_PRACTICES" numeric,
	"TRANSPARENCY_DISCLOSURE_PRACTICES" numeric,
	"FINANCIAL_SAFETY_PRACTICES" numeric,
	"NO_SUCCESSFUL_HIRES_POST_EXP" numeric,
	"TOTAL_HIRES" numeric,
	"PERC_COMMIT_WORK_HOURS" numeric,
	"NO_EXE_PRACTICES" numeric,
	"NO_PLANNED_PRACTICES" numeric,
	"NO_COMP_ELEMENTS" numeric,
	"TOTAL_ELEMENTS" numeric,
	"NO_TIMELY_REPORTS" numeric,
	"NO_REQUIRED_REPORTS" numeric,
	"NO_GRADES_BENEFITS_SATISF" numeric,
	"NO_RESPONSES_SATIS_FORM" numeric,
	"TOTAL_GRADES_EMP_SATIS" numeric,
	"NO_RESPONSES_EMP_SATIS" numeric,
	"TOTAL_GEADES_PARTENERS_SATIS" numeric,
	"TOTAL_RESPONSES_VOL_SATIS" numeric,
	"NO_RESPOSES_VOL_SATIS_FORM" numeric,
	"TOTAL_GRADES_VOL_STATIS" numeric,
	"NO_RESPONSES_VOL_SATIS_FORM" numeric,
	"TOTAL_SATIS_GRADES_ORG" numeric,
	"NO_ORG_MEMBERS" numeric,
	"TOTAL_GRADES_COM" numeric,
	"NO_RESPONSES_COM_SATIS" numeric,
	"TASKS_ACHIEVED_TIMELY_CEO" numeric,
	"TOTAL_PLANNED_TASKS_CEO" numeric,
	"AVG_EVAL_EMPS" numeric,
	"AVG_RES_SATIS_FORMS_EMP" numeric,
	"EMP_EVAL" numeric,
	"EMP_ACHIEVMENT_PERC" numeric
);
--> statement-breakpoint
CREATE TABLE "operationalEntries" (
	"id" text PRIMARY KEY NOT NULL,
	"clientId" text NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp,
	"NO_OPERATIONAL_GOALS_ACHIEVED" numeric,
	"NO_OPERATIONAL_GOALS_PLANNED" numeric,
	"NO_PROGRAMS_EXECUTED" numeric,
	"NO_PROGRAMS_PLANNED" numeric,
	"NO_TIMELY_ACTIVITIES" numeric,
	"TOTAL_PLANNED_ACTIVITIES" numeric,
	"APPROVED_BUDGET" numeric,
	"PLANNED_ACTUAL_DIFF" numeric,
	"NO_OUTPUTS_ACHIEVED" numeric,
	"TOTAL_TARGETED_OUTPUTS" numeric,
	"NO_ACTUAL_BENEFICIARIES" numeric,
	"PLANNED_TARGET_NUMBER" numeric,
	"NO_PROGRAMS_WITH_PARTICIPANTS" numeric,
	"NO_PROGRAMS_PROJECTS" numeric,
	"NO_TIMELY_TRANSACTIONS" numeric,
	"TOTAL_TRANSACTIONS" numeric,
	"NO_ARCHIVED_DOCS" numeric,
	"TOTAL_DOCS" numeric,
	"NO_VOLUNTEERS_CURRENT_QUARTER" numeric,
	"NO_VOLUNTEERS_NEXT_QUARTER" numeric,
	"NO_VOLUNTEERS_CONT_3" numeric,
	"TOTAL_VOLUNTEERS" numeric
);
--> statement-breakpoint
CREATE TABLE "operationalIndicators" (
	"id" text PRIMARY KEY NOT NULL,
	"clientId" text NOT NULL,
	"entriesId" text NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp,
	"OPS_PLAN_EXEC" numeric,
	"PRJKT_PRGM_MGMT" numeric,
	"EFFIC_INTERNAL_OPS" numeric,
	"VOLN_MGMT" numeric,
	"OPS_GOALS_ACH_PERC" numeric,
	"PGRM_PRJKS_EXEC_PERC" numeric,
	"EFFIC_PRJKS_EXEC" numeric,
	"EFFITV_PRJKS_PGRM" numeric,
	"VOLN_CONTR_PRJKS_EXEC" numeric,
	"QLY_SPEED_PROC_EXEC" numeric,
	"DOCS_ARCHIV" numeric,
	"VOLUN_GROWTH_RATE_QUAR" numeric,
	"VOLUN_SUST_PERC" numeric,
	"PRJKT_TIMELY_COMP_PERC" numeric,
	"BUDGET_COMMIT_PERC" numeric,
	"PRJK_GOALS_ACHV_PERC" numeric,
	"REACH_TARGET_AUD_PERC" numeric
);
--> statement-breakpoint
ALTER TABLE "corporateEntries" ADD CONSTRAINT "corporateEntries_clientId_user_id_fk" FOREIGN KEY ("clientId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operationalEntries" ADD CONSTRAINT "operationalEntries_clientId_user_id_fk" FOREIGN KEY ("clientId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operationalIndicators" ADD CONSTRAINT "operationalIndicators_clientId_user_id_fk" FOREIGN KEY ("clientId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operationalIndicators" ADD CONSTRAINT "operationalIndicators_entriesId_operationalEntries_id_fk" FOREIGN KEY ("entriesId") REFERENCES "public"."operationalEntries"("id") ON DELETE no action ON UPDATE no action;